name: Publish npm package

on:
  workflow_run:
   workflows: [Test npm package]
   types:
   - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
      - name: Install dependencies
        working-directory: ./
        run: npm ci
        
      - name: Build typescript
        working-directory: ./
        run: npm run build

      - name: Publish Node.js package
        working-directory: ./
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
