name: Test npm package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
      - name: Install dependencies
        working-directory: ./
        run: npm ci

      - name: Write serviceAccountKey.json
        run: 'echo "$FIREBASE_SERVICE_ACCOUNT" >> serviceAccountKey.json'
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{secrets.FIREBASE_SERVICE_ACCOUNT}}
          
        
      - name: Run test
        working-directory: ./
        run: npm run test
