name: Test npm package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_dir: ["firebase-admin-typescript"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
      - name: Install dependencies
        working-directory: ${{matrix.package_dir}}
        run: npm ci

      - name: Write serviceAccountKey.json
        run: echo ${{secrets.NPM_TOKEN}} >> serviceAccountKey.json
        
      - name: Run test
        working-directory: ${{matrix.package_dir}}
        run: npm run test