name: Publish npm package

on:
  workflow_run:
   workflows: [Test npm package]
   types:
   - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        package_dir: ["firebase-admin-typescript", "firebase-typescript", "react-native-firebase-typescript"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
      - name: Install dependencies
        working-directory: ${{matrix.package_dir}}
        run: npm ci
        
      - name: Build typescript
        working-directory: ${{matrix.package_dir}}
        run: npm run build
        
      - name: Copy README
        working-directory: ${{matrix.package_dir}}
        run: cp ../README.md README.md

      - name: Copy LICENSE
        working-directory: ${{matrix.package_dir}}
        run: cp ../LICENSE LICENSE

      - name: Publish Node.js package
        working-directory: ${{matrix.package_dir}}
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
