name: Publish GitHub documentation page

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
        working-directory: docs
      - name: Build docs
        run: npm run build
        working-directory: docs
      - name: Archive artifact
        run: tar --dereference --hard-dereference --directory=build -cvf artifact.tar
        working-directory: docs
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/artifact.tar
          retention-days: 1
          if-no-files-found: error