name: Publish GitHub documentation page

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
        working-directory: docs
      - name: Build docs
        run: npm run build
        working-directory: docs
      - name: Archive artifact
        run: tar -cvf artifact.tar build --dereference --hard-dereference
        working-directory: docs
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: docs/artifact.tar
          retention-days: 1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3